# NumPy

Stands For Numerical Python.

50 times faster than Python arrays. Stored in one place. Written c or c++

https://www.w3schools.com/python/numpy/default.asp



In [4]:
import numpy as np

arr = np.array([1,2,3,4])
lst = [7,8,9,20]
print(arr)
print(type(arr))
a=arr+lst

print(a)
for i in range(len(a)):
    print(a[i])


[1 2 3 4]
<class 'numpy.ndarray'>
[ 8 10 12 24]
8
10
12
24


In [5]:
# from tuple
t = np.array((1,2,3,4))
t

array([1, 2, 3, 4])

# Multi-Dimensional Arrays

In [6]:
a0 = np.array(23)
a1 = np.array([4,5,6,7,8])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]])
a3 = np.array(
    [
    # Level 1
    [
        [.000,.001,.002,.003,.004],
        [.010,.011,.012,.013,.014],
        [.020,.021,.022,.023,.024]
    ],
    # Level 2
    [
        [.100,.101,.102,.103,.104],
        [.110,.111,.112,.113,.114],
        [.120,.121,.122,.123,.124]
    ]
    ]  
    )
    # Needs same number of numbers
print(a0)
print(a1)
print(a2)
print(a3)

print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)



23
[4 5 6 7 8]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[[[0.    0.001 0.002 0.003 0.004]
  [0.01  0.011 0.012 0.013 0.014]
  [0.02  0.021 0.022 0.023 0.024]]

 [[0.1   0.101 0.102 0.103 0.104]
  [0.11  0.111 0.112 0.113 0.114]
  [0.12  0.121 0.122 0.123 0.124]]]
0
1
2
3


## Higher Dimensional Arrays

In [7]:
a5 = np.array([1,2,3,4], ndmin=5)
print(a5)
print(' ndims :', a5.ndim)

[[[[[1 2 3 4]]]]]
 ndims : 5


# NumPy Array Indexing

In [8]:
div = "--------   "
print(a1[0])
print(div)
print(a2)
print(div)
print(a2[1,1])
print(div)
print(a2[1])
print(div + 'a3')
print(a3)
print(div + 'a3[1]')
print(a3[1])
print(div +'a3[1,2]')
print(a3[1,2])


4
--------   
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
--------   
7
--------   
[ 6  7  8  9 10]
--------   a3
[[[0.    0.001 0.002 0.003 0.004]
  [0.01  0.011 0.012 0.013 0.014]
  [0.02  0.021 0.022 0.023 0.024]]

 [[0.1   0.101 0.102 0.103 0.104]
  [0.11  0.111 0.112 0.113 0.114]
  [0.12  0.121 0.122 0.123 0.124]]]
--------   a3[1]
[[0.1   0.101 0.102 0.103 0.104]
 [0.11  0.111 0.112 0.113 0.114]
 [0.12  0.121 0.122 0.123 0.124]]
--------   a3[1,2]
[0.12  0.121 0.122 0.123 0.124]


# Negative Indexing

Access from the end

In [9]:
print(a3[1,2,-1])
print(a3[1,2,-2])
print(a3[-1])

0.124
0.123
[[0.1   0.101 0.102 0.103 0.104]
 [0.11  0.111 0.112 0.113 0.114]
 [0.12  0.121 0.122 0.123 0.124]]


# Array Slicing

INCLUDES the first index but EXCLUDES the second index

If omit latter however goes all the way

In [10]:
print(a1)
print(div)
print(a1[0:2])
print(a1[2:])
print(a1[:3])
print(div +'a1[-3:]')
print(a1[-3:])
print(div)
print(a3[:2])
print(div +'a2' )
print(a2)
print(div +'a2[1, 2:4]' )
print(a2[1, 2:4])
print(div +'a2[0:2, 3] Row 0 to 1 col 4' )
print(a2[0:2, 3])
print(div +'a2[0:2, 3]' )
print(a2[1:3, 2])


[4 5 6 7 8]
--------   
[4 5]
[6 7 8]
[4 5 6]
--------   a1[-3:]
[6 7 8]
--------   
[[[0.    0.001 0.002 0.003 0.004]
  [0.01  0.011 0.012 0.013 0.014]
  [0.02  0.021 0.022 0.023 0.024]]

 [[0.1   0.101 0.102 0.103 0.104]
  [0.11  0.111 0.112 0.113 0.114]
  [0.12  0.121 0.122 0.123 0.124]]]
--------   a2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
--------   a2[1, 2:4]
[8 9]
--------   a2[0:2, 3] Row 0 to 1 col 4
[4 9]
--------   a2[0:2, 3]
[8 8]


# Defined Data Types


In [14]:
a = np.array([1,2,3,44], dtype = 'S')
print(a)
print(a.dtype)

a = np.array([1,2,3,44], dtype = 'i4')  # 4 byte integer
print(a)
print(a.dtype)

a = np.array(['a','2','3'], dtype = 'i')

[b'1' b'2' b'3' b'44']
|S2
[ 1  2  3 44]
int32


ValueError: invalid literal for int() with base 10: 'a'

In [23]:
aTable = np.array([
    ['Louis','Gail','Rachel','Sarah'],
    [63,64,17,17]
    ])

print(aTable)
print(aTable.dtype)
print(aTable[0])
print(aTable[1])
#n = aTable.size, aTable.ndi
n = 4
for i in range(n):
    print(aTable[0,i], aTable[1,i] )

[['Louis' 'Gail' 'Rachel' 'Sarah']
 ['63' '64' '17' '17']]
<U21
['Louis' 'Gail' 'Rachel' 'Sarah']
['63' '64' '17' '17']


TypeError: 'float' object cannot be interpreted as an integer