Stands For Numerical Python.

50 times faster than Python arrays. Stored in one place. Written c or c++

https://www.w3schools.com/python/numpy/default.asp



In [43]:
import numpy as np

arr = np.array([1,2,3,4])
lst = [7,8,9,20]
print(arr)
print(type(arr))
a=arr+lst

print(a)
for i in range(len(a)):
    print(a[i])


[1 2 3 4]
<class 'numpy.ndarray'>
[ 8 10 12 24]
8
10
12
24


In [44]:
# from tuple
t = np.array((1,2,3,4))
t

array([1, 2, 3, 4])

# Multi-Dimensional Arrays

In [45]:
a0 = np.array(23)
a1 = np.array([4,5,6,7,8])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[6,7,8,9,10]])
a3 = np.array(
    [
    # Level 1
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [6,7,8,9,10]
    ],
    # Level 2
    [
        [1,2,3,4,5],
        [6,7,8,9,10],
        [6,7,8,9,10]
    ]
    ]  
    )
    # Needs same number of numbers
print(a0)
print(a1)
print(a2)
print(a3)

print(a0.ndim)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)



23
[4 5 6 7 8]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 6  7  8  9 10]]]
0
1
2
3


## Higher Dimensional Arrays

In [46]:
a5 = np.array([1,2,3,4], ndmin=5)
print(a5)
print(' ndims :', a5.ndim)

[[[[[1 2 3 4]]]]]
 ndims : 5


# NumPy Array Indexing

In [58]:
div = "--------"
print(a1[0])
print(div)
print(a2)
print(div)
print(a2[1,1])
print(div)
print(a2[1])
print(div)
print(a3)
print(div)
print(a3[1])
print(div)
print(a3[1,2])


4
--------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
7
[ 6  7  8  9 10]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [ 6  7  8  9 10]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]
----
[ 6  7  8  9 10]
